package com.goudong.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("shop_cart", "id", Cart.class);
		arp.addMapping("shop_cart_item", "id", CartItem.class);
		arp.addMapping("shop_goods", "id", Goods.class);
		arp.addMapping("shop_letus", "id", Letus.class);
		arp.addMapping("shop_message", "id", Message.class);
		arp.addMapping("shop_user", "id", User.class);
	}
}

