package com.goudong.model;

import com.goudong.model.base.BaseLetus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Letus extends BaseLetus<Letus> {
	public static final Letus dao = new Letus().dao();
}
