package com.goudong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCartItem<M extends BaseCartItem<M>> extends Model<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setCartId(java.lang.Long cartId) {
		set("cart_id", cartId);
		return (M)this;
	}
	
	public java.lang.Long getCartId() {
		return getLong("cart_id");
	}

	public M setGoodId(java.lang.Long goodId) {
		set("good_id", goodId);
		return (M)this;
	}
	
	public java.lang.Long getGoodId() {
		return getLong("good_id");
	}

	public M setCreateAt(java.util.Date createAt) {
		set("create_at", createAt);
		return (M)this;
	}
	
	public java.util.Date getCreateAt() {
		return get("create_at");
	}

	public M setUpdate(java.util.Date update) {
		set("update", update);
		return (M)this;
	}
	
	public java.util.Date getUpdate() {
		return get("update");
	}

}
