package com.goudong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMessage<M extends BaseMessage<M>> extends Model<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setMessageContent(java.lang.String messageContent) {
		set("message_content", messageContent);
		return (M)this;
	}
	
	public java.lang.String getMessageContent() {
		return getStr("message_content");
	}

	public M setCreateAt(java.util.Date createAt) {
		set("create_at", createAt);
		return (M)this;
	}
	
	public java.util.Date getCreateAt() {
		return get("create_at");
	}

	public M setUpdateAt(java.util.Date updateAt) {
		set("update_at", updateAt);
		return (M)this;
	}
	
	public java.util.Date getUpdateAt() {
		return get("update_at");
	}

}
