package com.goudong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLetus<M extends BaseLetus<M>> extends Model<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setLetusContent(java.lang.String letusContent) {
		set("letus_content", letusContent);
		return (M)this;
	}
	
	public java.lang.String getLetusContent() {
		return getStr("letus_content");
	}

	public M setCreateAt(java.util.Date createAt) {
		set("create_at", createAt);
		return (M)this;
	}
	
	public java.util.Date getCreateAt() {
		return get("create_at");
	}

	public M setUpdateAt(java.util.Date updateAt) {
		set("update_at", updateAt);
		return (M)this;
	}
	
	public java.util.Date getUpdateAt() {
		return get("update_at");
	}

}
