package com.goudong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCart<M extends BaseCart<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserId(java.math.BigInteger userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.math.BigInteger getUserId() {
		return get("user_id");
	}

	public M setCreateAt(java.util.Date createAt) {
		set("create_at", createAt);
		return (M)this;
	}
	
	public java.util.Date getCreateAt() {
		return get("create_at");
	}

	public M setUpdateAt(java.util.Date updateAt) {
		set("update_at", updateAt);
		return (M)this;
	}
	
	public java.util.Date getUpdateAt() {
		return get("update_at");
	}

}
